---
title: "Untitled"
author: '520595273'
date: "2025-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(GEOquery)
library(limma)
```

```{r}
expr_df <- readRDS("expr_df_matched.rds")  
pheno_df <- readRDS("pheno_clean.rds")
```

```{r}
colnames(expr_df)
head(expr_df)
```

```{r}
colnames(pheno_df)
head(pheno_df)
```

```{r}
pheno_df$SampleID <- rownames(pheno_df)
all(colnames(expr_df) %in% pheno_df$SampleID)
```

```{r}
gene_variance <- apply(expr_df, 1, var)
top_genes <- names(sort(gene_variance, decreasing = TRUE))[1:200]
expr_df_top <- expr_df[top_genes, ]
```


```{r}
expr_for_pca <- t(expr_df_top)
pca_res <- prcomp(expr_for_pca, center = TRUE, scale. = TRUE)
pca_df <- as.data.frame(pca_res$x)
pca_df$SampleID <- rownames(pca_df)
merged_df <- merge(pca_df, pheno_df, by = "SampleID")
```

```{r}
ggplot(merged_df, aes(x = PC1, y = PC2, color = sex)) +
  geom_point(size = 2) +
  theme_minimal() +
  labs(title = "PCA by sex")
```

```{r}
ggplot(merged_df, aes(x = PC1, y = PC2, color = c3_status)) +
  geom_point(size = 2) +
  facet_wrap(~ c4_status) +  
  theme_bw() +
  labs(
    title = "PCA by C3 status (color) & C4 status (facet)",
    x = "PC1", y = "PC2",
    color = "C3 status"
  )
```

```{r}
ggplot(merged_df, aes(x = PC1, y = PC2, 
                      color = antidsdna_at_baseline)) +
  geom_point(size = 3) +
  theme_light() +
  labs(
    title = "PCA by anti-dsDNA (color) & sex (shape)",
    x = "PC1", y = "PC2",
    color = "anti-dsDNA",
    shape = "Sex"
  )
```

```{r}
merged_df$c3c4_combo <- paste(merged_df$c3_status, merged_df$c4_status, sep = "_")

ggplot(merged_df, aes(x = PC1, y = PC2, color = c3c4_combo)) +
  geom_point(size = 3) +
  theme_bw() +
  labs(
    title = "PCA by combined C3 and C4 status",
    x = "PC1", y = "PC2",
    color = "C3_C4"
  )
```



